brand = [
    "hp",
    "mio",
    "msi",
    "milwaukee electric tool corp.",
    "gigaram",
    "corsair",
    "sandisk",
    "crucial",
    "dell",
    "transcend",
    "gigabyte",
    "equallogic",
    "samsung",
    "asus",
    "intel",
    "kingston",
    "apple",
    "amd",
    "zebra",
    "vostro",
    "tp-link",
    "sun",
    "western digital",
    "zotac",
    "ultimate support",
    "fujitsu",
    "garmin",
    "silverstone",
    "asrock",
    "seagate",
    "icy box",
    "datalogic",
    "asustek",
    "targus",
    "startech",
    "sapphire",
    "microsoft",
    "apogee",
    "pny",
    "speck",
    "wd",
    "logitech",
    "hewlett packard enterprise",
    "buffalo",
    "startech.com",
    "zowie",
    "gossammer gear",
    "xps",
    "nzxt",
    "elpida",
    "optiplex",
    "trendnet",
    "evga",
    "alfa",
    "universal audio",
    "mobi lock",
    "lenovo",
    "korg",
    "amazonbasics",
    "acer",
    "supermicro",
    "topram",
    "antec",
    "steinberg",
    "pqi",
    "aoc",
    "kingston digital inc.",
    "hynix",
    "सैमसंग",
    "nanya",
    "amazon",
    "dicota",
    "epson",
    "symbol",
    "generic",
    "milwaukee",
    "corsair microsystems inc.",
    "d-link",
    "digi",
    "n1",
    "ibm",
    "coolermaster",
    "benq",
    "mobi locktm",
    "ocuk extreme",
    "twinmos",
    "integral",
    "a-data",
    "g.skill",
    "apacer",
    "pny technologies",
    "infineon",
    "sony",
    "yli",
    "steinberg ur22mkii",
    "toshiba",
    "istorage",
    "netgear",
    "atp",
    "tripp lite",
]

brands_mapping = {
    "hp": ["hp"],
    "mio": ["mio"],
    "msi": ["msi"],
    "milwaukee electric tool corp.": ["milwaukee electric tool corp.", "milwaukee"],
    "gigaram": ["gigaram"],
    "corsair": ["corsair"],
    "sandisk": ["sandisk"],
    "crucial": ["crucial"],
    "dell": ["dell"],
    "transcend": ["transcend"],
    "gigabyte": ["gigabyte"],
    "equallogic": ["equallogic"],
    "samsung": ["samsung"],
    "asus": ["asus"],
    "intel": ["intel"],
    "kingston": ["kingston"],
    "apple": ["apple", "mac"],
    "amd": ["amd"],
    "zebra": ["zebra"],
    "vostro": ["vostro"],
    "tp-link": ["tp-link"],
    "sun": ["sun"],
    "western digital": ["western digital", "wd"],
    "zotac": ["zotac"],
    "ultimate support": ["ultimate support"],
    "fujitsu": ["fujitsu"],
    "garmin": ["garmin"],
    "silverstone": ["silverstone"],
    "asrock": ["asrock"],
    "seagate": ["seagate"],
    "icy box": ["icy"],
    "datalogic": ["datalogic"],
    "asustek": ["asustek"],
    "targus": ["targus"],
    "startech": ["startech"],
    "sapphire": ["sapphire"],
    "microsoft": ["microsoft"],
    "apogee": ["apogee"],
    "pny": ["pny"],
    "speck": ["speck"],
    "logitech": ["logitech"],
    "hewlett packard enterprise": ["hewlett packard enterprise", "hewlett"],  # clenup
    "buffalo": ["buffalo"],
    "startech.com": ["startech.com"],  # clenup
    "zowie": ["zowie"],
    "gossammer gear": ["gossammer gear"],
    "xps": ["xps"],
    "nzxt": ["nzxt"],
    "elpida": ["elpida"],
    "optiplex": ["optiplex"],
    "trendnet": ["trendnet"],
    "evga": ["evga"],
    "alfa": ["alfa"],
    "universal audio": ["universal audio"],
    "mobi lock": ["mobi lock"],
    "lenovo": ["lenovo"],
    "korg": ["korg"],
    "amazonbasics": ["amazonbasics"],
    "acer": ["acer"],
    "supermicro": ["supermicro"],
    "topram": ["topram"],
    "antec": ["antec"],
    "steinberg": ["steinberg"],
    "pqi": ["pqi"],
    "aoc": ["aoc"],
    "kingston digital inc.": ["kingston digital inc."],  # clenup
    "hynix": ["hynix"],
    "सैमसंग": ["सैमसंग"],
    "nanya": ["nanya"],
    "amazon": ["amazon"],
    "dicota": ["dicota"],
    "epson": ["epson"],
    "symbol": ["symbol"],
    "generic": ["generic"],
    "milwaukee": ["milwaukee"],
    "corsair microsystems inc.": ["corsair microsystems inc."],  # clenup
    "d-link": ["d-link"],
    "digi": ["digi"],
    "n1": ["n1"],
    "ibm": ["ibm"],
    "coolermaster": ["coolermaster"],
    "benq": ["benq"],
    "mobi locktm": ["mobi locktm"],
    "ocuk extreme": ["ocuk extreme"],
    "twinmos": ["twinmos"],
    "integral": ["integral"],
    "a-data": ["a-data"],
    "g.skill": ["g.skill"],
    "apacer": ["apacer"],
    "pny technologies": ["pny technologies"],  # clenup
    "infineon": ["infineon"],
    "sony": ["sony"],
    "yli": ["yli"],
    "steinberg ur22mkii": ["steinberg ur22mkii"],
    "toshiba": ["toshiba"],
    "istorage": ["istorage"],
    "netgear": ["netgear"],
    "atp": ["atp"],
    "tripp lite": ["tripp lite"],
}
