brands = [
    "hp",
    "mio",
    "msi",
    "milwaukee electric tool corp.",
    "gigaram",
    "corsair",
    "sandisk",
    "crucial",
    "dell",
    "transcend",
    "gigabyte",
    "equallogic",
    "samsung",
    "asus",
    "intel",
    "kingston",
    "apple",
    "amd",
    "zebra",
    "vostro",
    "tp-link",
    "sun",
    "western digital",
    "zotac",
    "ultimate support",
    "fujitsu",
    "garmin",
    "silverstone",
    "asrock",
    "seagate",
    "icy box",
    "datalogic",
    "asustek",
    "targus",
    "startech",
    "sapphire",
    "microsoft",
    "apogee",
    "pny",
    "speck",
    "wd",
    "logitech",
    "buffalo",
    "startech.com",
    "zowie",
    "gossammer gear",
    "xps",
    "nzxt",
    "elpida",
    "optiplex",
    "trendnet",
    "evga",
    "alfa",
    "universal audio",
    "mobi lock",
    "lenovo",
    "korg",
    "amazonbasics",
    "acer",
    "supermicro",
    "topram",
    "antec",
    "steinberg",
    "pqi",
    "aoc",
    "kingston digital inc.",
    "hynix",
    "सैमसंग",
    "nanya",
    "amazon",
    "dicota",
    "epson",
    "symbol",
    "generic",
    "milwaukee",
    "corsair microsystems inc.",
    "d-link",
    "digi",
    "n1",
    "ibm",
    "coolermaster",
    "benq",
    "mobi locktm",
    "ocuk extreme",
    "twinmos",
    "integral",
    "a-data",
    "g.skill",
    "apacer",
    "infineon",
    "sony",
    "yli",
    "toshiba",
    "istorage",
    "netgear",
    "atp",
    "tripp lite",
]

# Brand mapping dictionary for NER model to match user input to standardized brand names
# Each entry maps a canonical brand name to various ways users might refer to it
brands_mapping = {
    # Major Computer Brands
    "hp": ["hp", "hewlett packard", "hewlett-packard", "h.p.", "h p"],
    "dell": ["dell", "dell computers", "dell inc", "dell computer"],
    "lenovo": ["lenovo", "lenovo group", "lenovo computers", "thinkpad"],
    "asus": ["asus", "asustek", "asus computer", "asus rog", "republic of gamers", "asus networking", "asus router", "asus wifi"],
    "acer": ["acer", "acer inc", "acer computer"],
    "msi": ["msi", "micro-star international", "micro star", "micro star international", "micro-star", "msi gaming", "msi computer"],
    "microsoft": ["microsoft", "microsoft corporation", "microsoft corp", "msft", "surface"],
    "toshiba": ["toshiba", "toshiba america", "toshiba corp", "toshiba storage", "toshiba hard drive"],
    "fujitsu": ["fujitsu", "fujitsu ltd", "fujitsu limited"],
    "ibm": ["ibm", "international business machines", "i.b.m.", "i b m"],
    
    # Mobile & Electronics Brands
    "apple": ["apple", "apple inc", "apple computer", "iphone", "ipad", "macbook", "mac", "imac", 
             "apple computer inc", "ipod", "apple watch", "watch", "mac mini", "macmini", "mac pro", 
             "macpro", "apple tv", "appletv", "airpods", "air pods", "homepod", "home pod", 
             "apple pencil", "magic keyboard", "magic mouse", "magic trackpad"],
    "samsung": ["samsung", "samsung electronics", "samsung corp", "samsung galaxy", "galaxy", "samsung ssd", "samsung storage", "samsung memory", "samsung semiconductor"],
    "sony": ["sony", "sony corporation", "sony electronics", "sony corp", "sony alpha", "sony camera", "sony digital"],
    "lg": ["lg", "lg electronics", "lg corp", "lg electronic"],
    "huawei": ["huawei", "huawei technologies", "huawei tech"],
    "motorola": ["motorola", "moto", "motorola inc", "motorola mobility"],
    "nokia": ["nokia", "nokia corp", "nokia corporation"],
    "xiaomi": ["xiaomi", "mi", "xiaomi corp", "xiaomi tech"],
    "oneplus": ["oneplus", "one plus", "1plus", "1+", "oneplus tech"],
    "google": ["google", "google inc", "google llc", "google pixel", "pixel"],
    
    # Computer Components
    "intel": ["intel", "intel corp", "intel corporation", "intel processor", "core i7", "core i5", "core i9", "intel cpu"],
    "amd": ["amd", "advanced micro devices", "a.m.d.", "a m d", "ryzen", "amd cpu", "amd processor"],
    "nvidia": ["nvidia", "nvidia corp", "nvidia corporation", "nvidia gpu", "geforce", "rtx", "gtx"],
    "corsair": ["corsair", "corsair gaming", "corsair components", "corsair microsystems", "corsair microsystems inc"],
    "gigabyte": ["gigabyte", "gigabyte technology", "gigabyte tech", "aorus"],
    "asrock": ["asrock", "asrock inc", "asrock corporation"],
    "evga": ["evga", "evga corporation", "e v g a"],
    "zotac": ["zotac", "zotac international", "zotac gaming"],
    "nzxt": ["nzxt", "n z x t", "n.z.x.t"],
    "coolermaster": ["coolermaster", "cooler master", "cm", "cooler-master"],
    "silverstone": ["silverstone", "silverstone tech", "silverstone technology"],
    "antec": ["antec", "antec inc", "antec corp"],
    "g.skill": ["g.skill", "g skill", "gskill", "g-skill"],
    
    # Storage Brands
    "western digital": ["western digital", "wd digital", "western digital corp", "western dig"],
    "seagate": ["seagate", "seagate technology", "seagate tech", "seagate corp"],
    "sandisk": ["sandisk", "sandisk corp", "sandisk corporation", "sand disk", "san disk"],
    "kingston": ["kingston", "kingston technology", "kingston digital", "kingston digital inc", "kingston technology company"],
    "crucial": ["crucial", "crucial technology", "crucial tech", "crucial memory"],
    "transcend": ["transcend", "transcend information", "transcend info", "transcend corp"],
    "hynix": ["hynix", "sk hynix", "sk hynix inc", "hynix semiconductor", "sk memory"],
    "pny": ["pny", "pny technologies", "pny tech", "pny corp"],
    "a-data": ["a-data", "adata", "a data", "adata technology"],
    "apacer": ["apacer", "apacer technology", "apacer tech"],
    
    # Networking Brands
    "tp-link": ["tp-link", "tp link", "tplink", "t p link"],
    "netgear": ["netgear", "netgear inc", "netgear router", "netgear corporation"],
    "cisco": ["cisco", "cisco systems", "cisco network", "cisco corporation"],
    "d-link": ["d-link", "dlink", "d link", "d.link", "d link systems"],
    "linksys": ["linksys", "cisco linksys", "linksys router", "linksys wifi"],
    "ubiquiti": ["ubiquiti", "ubiquiti networks", "ubiquiti systems", "unifi"],
    "buffalo": ["buffalo", "buffalo technology", "buffalo tech", "buffalo inc"],
    "trendnet": ["trendnet", "trend net", "trend-net", "trendnet router"],
    
    # Peripheral Brands
    "logitech": ["logitech", "logitech international", "logi", "logitech g"],
    "razer": ["razer", "razer inc", "razer gaming", "razer usa"],
    "steelseries": ["steelseries", "steel series", "steel-series"],
    "hyperx": ["hyperx", "hyper x", "hyper-x", "kingston hyperx"],
    "benq": ["benq", "ben q", "ben-q", "benq corporation"],
    "aoc": ["aoc", "a.o.c.", "a o c", "aoc monitor"],
    "viewsonic": ["viewsonic", "view sonic", "view-sonic", "viewsonic corp"],
    "epson": ["epson", "epson corporation", "epson printer", "epson scanner"],
    "targus": ["targus", "targus inc", "targus group"],
    "sennheiser": ["sennheiser", "sennheiser electronic", "sennheiser headphones"],
    "bose": ["bose", "bose corporation", "bose speakers", "bose headphones"],
    "jbl": ["jbl", "j.b.l.", "j b l", "jbl speakers", "jbl audio"],
    
    # Tool Brands
    "milwaukee": ["milwaukee", "milwaukee tool", "milwaukee electric tool", "milwaukee electric tool corp", "milwaukee electric"],
    "dewalt": ["dewalt", "de walt", "de-walt", "dewalt tools", "dewalt power tools"],
    "bosch": ["bosch", "bosch tools", "bosch power tools", "robert bosch"],
    "makita": ["makita", "makita tools", "makita corporation", "makita power tools"],
    "stanley": ["stanley", "stanley tools", "stanley black & decker", "stanley black and decker"],
    "craftsman": ["craftsman", "craftsman tools", "sears craftsman", "craftsman professional"],
    
    # Camera Brands
    "canon": ["canon", "canon inc", "canon camera", "canon eos"],
    "nikon": ["nikon", "nikon corporation", "nikon camera", "nikon corp"],
    "fujifilm": ["fujifilm", "fuji film", "fuji", "fujifilm corporation", "fuji camera"],
    "olympus": ["olympus", "olympus corporation", "olympus camera", "olympus digital"],
    "panasonic": ["panasonic", "panasonic corporation", "panasonic camera", "panasonic lumix", "lumix"],
    "gopro": ["gopro", "go pro", "go-pro", "gopro camera", "gopro action"],
    "leica": ["leica", "leica camera", "leica ag", "leitz"],
    
    # Musical Instrument Brands
    "yamaha": ["yamaha", "yamaha corporation", "yamaha music", "yamaha musical", "yamaha instruments"],
    "roland": ["roland", "roland corporation", "roland music", "roland musical"],
    "fender": ["fender", "fender musical instruments", "fender guitar", "fender electric"],
    "gibson": ["gibson", "gibson guitar", "gibson brands", "gibson usa"],
    "korg": ["korg", "korg inc", "korg synthesizer", "korg keyboard"],
    "steinberg": ["steinberg", "steinberg media", "steinberg audio", "steinberg ur22mkii", "steinberg ur22"],
    "universal audio": ["universal audio", "ua", "uaudio", "universal audio inc"],
    
    # E-commerce Brands
    "amazon": ["amazon", "amazon.com", "amazon basics", "amazonbasics", "amazon basic", "amazon prime"],
    "amazonbasics": ["amazonbasics", "amazon basics", "amazon basic", "basics"],
    
    # Other Brands (keeping original mappings that weren't expanded above)
    "mio": ["mio", "mio navigation", "mio technology", "mio gps"],
    "gigaram": ["gigaram", "giga ram", "giga-ram"],
    "equallogic": ["equallogic", "equal logic", "equal-logic", "dell equallogic"],
    "zebra": ["zebra", "zebra technologies", "zebra tech", "zebra scanner"],
    "vostro": ["vostro", "dell vostro", "vostro laptop"],
    "sun": ["sun", "sun microsystems", "sun micro", "oracle sun"],
    "ultimate support": ["ultimate support", "ultimate support systems", "ultimate stands"],
    "garmin": ["garmin", "garmin international", "garmin gps", "garmin navigation"],
    "icy box": ["icy box", "icybox", "icy-box", "raidsonic icy box", "raidsonic"],
    "datalogic": ["datalogic", "data logic", "data-logic", "datalogic scanning"],
    "startech": ["startech", "startech.com", "star tech", "star-tech", "startech components"],
    "sapphire": ["sapphire", "sapphire technology", "sapphire tech", "sapphire radeon"],
    "apogee": ["apogee", "apogee digital", "apogee electronics", "apogee sound"],
    "speck": ["speck", "speck products", "speck cases", "speck fitted"],
    "zowie": ["zowie", "zowie gear", "benq zowie", "zowie mouse"],
    "gossammer gear": ["gossammer gear", "gossamer gear", "gossamer", "gossammer"],
    "xps": ["xps", "dell xps", "xps laptop", "xps computer"],
    "elpida": ["elpida", "elpida memory", "elpida semiconductor"],
    "optiplex": ["optiplex", "dell optiplex", "optiplex desktop"],
    "alfa": ["alfa", "alfa network", "alfa wifi", "alfa wireless"],
    "mobi lock": ["mobi lock", "mobilock", "mobi-lock", "mobi locktm"],
    "supermicro": ["supermicro", "super micro", "super-micro", "supermicro computer"],
    "topram": ["topram", "top ram", "top-ram"],
    "pqi": ["pqi", "p.q.i.", "p q i", "pqi memory"],
    "nanya": ["nanya", "nanya technology", "nanya tech", "nanya semiconductor"],
    "dicota": ["dicota", "dicota ag", "dicota bag", "dicota case"],
    "symbol": ["symbol", "symbol technologies", "symbol scanner", "symbol barcode"],
    "generic": ["generic", "generics", "generic brand", "unbranded", "no brand"],
    "digi": ["digi", "digi international", "digi connect", "digi one"],
    "n1": ["n1", "n-1", "n 1", "n one"],
    "ocuk extreme": ["ocuk extreme", "ocuk", "overclockers uk extreme", "overclockers extreme"],
    "twinmos": ["twinmos", "twin mos", "twin-mos", "twinmos technologies"],
    "integral": ["integral", "integral memory", "integral flash", "integral storage"],
    "infineon": ["infineon", "infineon technologies", "infineon tech", "infineon semiconductor"],
    "yli": ["yli", "y.l.i.", "y l i", "yli electronic", "yali"],
    "istorage": ["istorage", "i-storage", "i storage", "istorage secure"],
    "atp": ["atp", "a.t.p.", "a t p", "atp electronics", "atp memory"],
    "tripp lite": ["tripp lite", "tripp-lite", "tripp", "tripplite", "tripp lite power"],
}
